/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-29 08:19:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.model.JobTypeModel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.JobTypeModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");

if (session.getAttribute("email") == null) {
	response.sendRedirect("login.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>Home Page - Job Consulting</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/boxicons/css/boxicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/glightbox/css/glightbox.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Header ======= -->\r\n");
      out.write("	<header id=\"header\" class=\"fixed-top\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container d-flex align-items-center justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("			<h1 class=\"logo\">\r\n");
      out.write("				<a href=\"index.html\">Job Consulting</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<!-- \r\n");
      out.write("								<li><a class=\"nav-link scrollto active\" href=\"#hero\">Home</a></li>\r\n");
      out.write("							 -->\r\n");
      out.write("					<li style=\"margin-left: 10px;\">");
      out.print(session.getAttribute("name"));
      out.write("</span>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li onClick=\"Logout()\"><a class=\"getstarted scrollto\"\r\n");
      out.write("						href=\"logout\">Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<i class=\"bi bi-list mobile-nav-toggle\"></i>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<!-- .navbar -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("	<main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Normal User Area -->\r\n");
      out.write("		<div id=\"normalUser\" style=\"display: none; min-height: 580px\">\r\n");
      out.write("			<section id=\"about\" class=\"about mt-5\">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row content\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"section-title\">\r\n");
      out.write("								<p>User Home Page</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("							<form action=\"book-appointment\" method=\"post\">\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Job Type</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"jobType\" name=\"jobType\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Software Engineer</option>\r\n");
      out.write("											<option value=\"2\">Teacher</option>\r\n");
      out.write("											<option value=\"3\">Doctor</option>\r\n");
      out.write("										</select>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Consultant</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"consultant\" name=\"consultant\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Bob Harizon</option>\r\n");
      out.write("											<option value=\"2\">John Smith</option>\r\n");
      out.write("										</select> <select class=\"form-control\" id=\"jobTypeSelect\"\r\n");
      out.write("											name=\"jobTypeSelect\">\r\n");
      out.write("											");

											List<JobTypeModel> jobTypes = (List<JobTypeModel>) request.getAttribute("jobType");
											if (jobTypes != null) {
												for (JobTypeModel jobType : jobTypes) {
											
      out.write("\r\n");
      out.write("											<option value=\"");
      out.print(jobType.getId());
      out.write('"');
      out.write('>');
      out.print(jobType.getName());
      out.write("</option>\r\n");
      out.write("											");

											}
											}
											
      out.write("\r\n");
      out.write("										</select> <select id=\"jobTypeSelect\" name=\"jobTypeSelect\">\r\n");
      out.write("											<!-- Options will be inserted here -->\r\n");
      out.write("										</select> <select id=\"jobTypeSelect\">\r\n");
      out.write("											<c:forEach var=\"jobType\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jobTypeList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("												<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jobType.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jobType.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("											</c:forEach>\r\n");
      out.write("										</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Date</label> <input type=\"date\" name=\"\"\r\n");
      out.write("											id=\"\" class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Time</label> <input type=\"time\" name=\"\"\r\n");
      out.write("											id=\"\" class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<button type=\"clear\" class=\"btn btn-danger mb-2 col-sm-12\">Clear</button>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary col-sm-12 mb-2\">Book\r\n");
      out.write("											Appointment</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section id=\"counts\" class=\"counts\">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("					<div class=\"section-title\">\r\n");
      out.write("						<h2>Consultant</h2>\r\n");
      out.write("						<p>Appointment List</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row no-gutters\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-12 col-md-6 d-md-flex align-items-md-stretch\">\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">#</th>\r\n");
      out.write("										<th scope=\"col\">Job Type</th>\r\n");
      out.write("										<th scope=\"col\">Consultant</th>\r\n");
      out.write("										<th scope=\"col\">Date</th>\r\n");
      out.write("										<th scope=\"col\">Time</th>\r\n");
      out.write("										<th scope=\"col\">Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">1</th>\r\n");
      out.write("										<td>Software Engineer</td>\r\n");
      out.write("										<td>Bob Harizon</td>\r\n");
      out.write("										<td>29/08/2023</td>\r\n");
      out.write("										<td>8.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">2</th>\r\n");
      out.write("										<td>Software Engineer</td>\r\n");
      out.write("										<td>John Smith</td>\r\n");
      out.write("										<td>30/08/2023</td>\r\n");
      out.write("										<td>8.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Consultant User Area -->\r\n");
      out.write("		<div id=\"ConsultUser\" style=\"display: none; min-height: 580px\">\r\n");
      out.write("			<section id=\"about\" class=\"about mt-5\">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("					<div class=\"row content\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<form action=\"add-consult\" method=\"post\">\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Date</label> <input type=\"date\"\r\n");
      out.write("											name=\"date\" id=\"date\" class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Time</label> <input type=\"time\"\r\n");
      out.write("											name=\"time\" id=\"\" time class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-12 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Job Type</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"exampleFormControlSelect1\"\r\n");
      out.write("											name=\"jobType\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Software Engineer</option>\r\n");
      out.write("											<option value=\"2\">Teacher</option>\r\n");
      out.write("											<option value=\"3\">Doctor</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<button type=\"clear\" class=\"btn btn-danger mb-2 col-sm-12\">Clear</button>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary col-sm-12 mb-2\">Set\r\n");
      out.write("											Available Time</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"section-title\">\r\n");
      out.write("								<h2>Consultant</h2>\r\n");
      out.write("								<p>Available Time</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">#</th>\r\n");
      out.write("										<th scope=\"col\">Job Type</th>\r\n");
      out.write("										<th scope=\"col\">Date</th>\r\n");
      out.write("										<th scope=\"col\">Time</th>\r\n");
      out.write("										<th scope=\"col\">Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">1</th>\r\n");
      out.write("										<td>Software Engineering</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>8.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">2</th>\r\n");
      out.write("										<td>Doctor</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>10.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section id=\"counts\" class=\"counts\">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("					<div class=\"section-title\">\r\n");
      out.write("						<h2>Consultant</h2>\r\n");
      out.write("						<p>Appointment List</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row no-gutters\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-12 col-md-6 d-md-flex align-items-md-stretch\">\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">#</th>\r\n");
      out.write("										<th scope=\"col\">Name</th>\r\n");
      out.write("										<th scope=\"col\">Job Type</th>\r\n");
      out.write("										<th scope=\"col\">Date</th>\r\n");
      out.write("										<th scope=\"col\">Time</th>\r\n");
      out.write("										<th scope=\"col\">Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">1</th>\r\n");
      out.write("										<td>Asanka</td>\r\n");
      out.write("										<td>Software Engineering</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>8.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">2</th>\r\n");
      out.write("										<td>Smith</td>\r\n");
      out.write("										<td>Doctor</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>10.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Admin User Area -->\r\n");
      out.write("		<div id=\"adminUser\" style=\"display: none; min-height: 580px\">\r\n");
      out.write("			<section id=\"about\" class=\"about mt-5 \">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("					<div class=\"row content\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"row content\">\r\n");
      out.write("								<div class=\"section-title mt-4\">\r\n");
      out.write("									<h2>Consultant Available Time</h2>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-lg-6\">\r\n");
      out.write("									<form action=\"admin-add-consult\" method=\"post\">\r\n");
      out.write("										<div class=\"form-group row\">\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<label class=\"mb-2\">Date</label> <input type=\"date\"\r\n");
      out.write("													name=\"date\" id=\"date\" class=\"form-control\" />\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<label class=\"mb-2\">Time</label> <input type=\"time\"\r\n");
      out.write("													name=\"time\" id=\"\" time class=\"form-control\" />\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<label class=\"mb-2\">Job Type</label> <select\r\n");
      out.write("													class=\"form-control\" id=\"exampleFormControlSelect1\"\r\n");
      out.write("													name=\"jobType\">\r\n");
      out.write("													<option></option>\r\n");
      out.write("													<option value=\"1\">Software Engineer</option>\r\n");
      out.write("													<option value=\"2\">Teacher</option>\r\n");
      out.write("													<option value=\"3\">Doctor</option>\r\n");
      out.write("												</select>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<label class=\"mb-2\">Consultant</label> <select\r\n");
      out.write("													class=\"form-control\" id=\"exampleFormControlSelect1\"\r\n");
      out.write("													name=\"conUser\">\r\n");
      out.write("													<option></option>\r\n");
      out.write("													<option value=\"1\">Bob Harizon</option>\r\n");
      out.write("													<option value=\"2\">John Smith</option>\r\n");
      out.write("												</select>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<button type=\"clear\" class=\"btn btn-danger mb-2 col-sm-12\">Clear</button>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("												<button type=\"submit\" class=\"btn btn-primary col-sm-12 mb-2\">Set\r\n");
      out.write("													Available Time</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<table class=\"table table-hover\">\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th scope=\"col\">#</th>\r\n");
      out.write("												<th scope=\"col\">Job Type</th>\r\n");
      out.write("												<th scope=\"col\">Consultant</th>\r\n");
      out.write("												<th scope=\"col\">Date</th>\r\n");
      out.write("												<th scope=\"col\">Time</th>\r\n");
      out.write("												<th scope=\"col\">Action</th>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th scope=\"row\">1</th>\r\n");
      out.write("												<td>Software Engineering</td>\r\n");
      out.write("												<td>Bob Harizon</td>\r\n");
      out.write("												<td>28/08/2023</td>\r\n");
      out.write("												<td>8.30 PM</td>\r\n");
      out.write("												<td>\r\n");
      out.write("													<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("														<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("													</button>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th scope=\"row\">2</th>\r\n");
      out.write("												<td>Doctor</td>\r\n");
      out.write("												<td>Bob Harizon</td>\r\n");
      out.write("												<td>28/08/2023</td>\r\n");
      out.write("												<td>10.30 PM</td>\r\n");
      out.write("												<td>\r\n");
      out.write("													<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("														<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("													</button>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section id=\"counts\" class=\"counts\">\r\n");
      out.write("				<div class=\"container\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row no-gutters\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"row content mt-4\">\r\n");
      out.write("								<div class=\"section-title\">\r\n");
      out.write("									<h2>All Booking</h2>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("							<form action=\"admin-book-appointment\" method=\"post\">\r\n");
      out.write("								<div class=\"form-group row\">\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Job Type</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"jobType\" name=\"jobType\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Software Engineer</option>\r\n");
      out.write("											<option value=\"2\">Teacher</option>\r\n");
      out.write("											<option value=\"3\">Doctor</option>\r\n");
      out.write("										</select>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Consultant</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"consultant\" name=\"consultant\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Bob Harizon</option>\r\n");
      out.write("											<option value=\"2\">John Smith</option>\r\n");
      out.write("										</select>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Date</label> <input type=\"date\" name=\"\"\r\n");
      out.write("											id=\"\" class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Time</label> <input type=\"time\" name=\"\"\r\n");
      out.write("											id=\"\" class=\"form-control\" />\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\">Appointment User</label> <select\r\n");
      out.write("											class=\"form-control\" id=\"appUser\" name=\"appUser\">\r\n");
      out.write("											<option></option>\r\n");
      out.write("											<option value=\"1\">Asanka Yaparathna</option>\r\n");
      out.write("											<option value=\"2\">Teacher</option>\r\n");
      out.write("											<option value=\"3\">Doctor</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-sm-6 mb-2\">\r\n");
      out.write("										<label class=\"mb-2\"></label>\r\n");
      out.write("										<button type=\"submit\"\r\n");
      out.write("											class=\"btn btn-primary col-sm-12 mb-2 mt-1\">Book\r\n");
      out.write("											Appointment</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">#</th>\r\n");
      out.write("										<th scope=\"col\">Name</th>\r\n");
      out.write("										<th scope=\"col\">Job Type</th>\r\n");
      out.write("										<th scope=\"col\">Date</th>\r\n");
      out.write("										<th scope=\"col\">Time</th>\r\n");
      out.write("										<th scope=\"col\">Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">1</th>\r\n");
      out.write("										<td>Asanka</td>\r\n");
      out.write("										<td>Software Engineering</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>8.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">2</th>\r\n");
      out.write("										<td>Smith</td>\r\n");
      out.write("										<td>Doctor</td>\r\n");
      out.write("										<td>28/08/2023</td>\r\n");
      out.write("										<td>10.30 PM</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-danger\">\r\n");
      out.write("												<i class=\"ri-delete-bin-line\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Footer ======= -->\r\n");
      out.write("	<footer id=\"footer\" class=\"mt-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"copyright\">\r\n");
      out.write("				&copy; Copyright <strong><span>Job Consulting</span></strong>. All\r\n");
      out.write("				Rights Reserved\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- \r\n");
      out.write("      \r\n");
      out.write("      	<div class=\"credits\">\r\n");
      out.write("       Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("       -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("	<div id=\"preloader\"></div>\r\n");
      out.write("	<a href=\"#\"\r\n");
      out.write("		class=\"back-to-top d-flex align-items-center justify-content-center\"><i\r\n");
      out.write("		class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Vendor JS Files -->\r\n");
      out.write("	<script src=\"assets/vendor/purecounter/purecounter_vanilla.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Main JS File -->\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendor/alert/sweetalert.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("		const currentURL = window.location.href;\r\n");
      out.write("		const protocol = window.location.protocol;\r\n");
      out.write("		const host = window.location.host;\r\n");
      out.write("		const hostUrl = protocol+\"//\"+host+\"/JobConsulting\";\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("		var status = '");
      out.print(session.getAttribute("status"));
      out.write("';\r\n");
      out.write("		var massage = '");
      out.print(session.getAttribute("massage"));
      out.write("';\r\n");
      out.write("		const value = sessionStorage.getItem('indexKey');\r\n");
      out.write("\r\n");
      out.write("		if (status != null && status == \"false\" && value == null) {\r\n");
      out.write("			swal(\"Error!\", massage, \"error\");\r\n");
      out.write("			sessionStorage.setItem('indexKey', 1);\r\n");
      out.write("		} else if (status != null && status == \"true\" && value == null) {\r\n");
      out.write("			swal(\"Success!\", massage, \"success\");\r\n");
      out.write("			sessionStorage.setItem('indexKey', 1);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		function Logout() {\r\n");
      out.write("			sessionStorage.clear();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		LoadUserDiv();\r\n");
      out.write("\r\n");
      out.write("		function LoadUserDiv() {\r\n");
      out.write("			if (status != null && status == \"true\") {\r\n");
      out.write("				const logedUserType = \"");
      out.print(session.getAttribute("userType"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("				var normal = document.getElementById(\"normalUser\");\r\n");
      out.write("				var admin = document.getElementById(\"adminUser\");\r\n");
      out.write("				var consult = document.getElementById(\"ConsultUser\");\r\n");
      out.write("\r\n");
      out.write("				if (logedUserType == \"Normal User\") {\r\n");
      out.write("					normal.style.display = \"block\";\r\n");
      out.write("					admin.style.display = \"none\";\r\n");
      out.write("					consult.style.display = \"none\";\r\n");
      out.write("				}\r\n");
      out.write("				if (logedUserType == \"Consultant\") {\r\n");
      out.write("					normal.style.display = \"none\";\r\n");
      out.write("					consult.style.display = \"block\";\r\n");
      out.write("					admin.style.display = \"none\";\r\n");
      out.write("				}\r\n");
      out.write("				if (logedUserType == \"Admin\") {\r\n");
      out.write("					normal.style.display = \"none\";\r\n");
      out.write("					admin.style.display = \"block\";\r\n");
      out.write("					consult.style.display = \"none\";\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		LoadJobType();\r\n");
      out.write("		function LoadJobType1(){\r\n");
      out.write("			debugger;\r\n");
      out.write("			const jobtypeUrl = hostUrl+'/get-job-type';\r\n");
      out.write("			fetch(jobtypeUrl)\r\n");
      out.write("            .then(response => response.json()) \r\n");
      out.write("            .then(data => {\r\n");
      out.write("                const jobTypeSelect = document.getElementById('jobTypeSelect');\r\n");
      out.write("\r\n");
      out.write("				debugger;\r\n");
      out.write("                data.forEach(jobType => {\r\n");
      out.write("                    const option = document.createElement('option');\r\n");
      out.write("                    option.value = jobType.id;\r\n");
      out.write("                    option.textContent = jobType.name;\r\n");
      out.write("                    jobTypeSelect.appendChild(option);\r\n");
      out.write("                });\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                console.log('Error:', error);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		function LoadJobType() {\r\n");
      out.write("		    const jobtypeUrl = hostUrl + '/get-job-type';\r\n");
      out.write("		    fetch(jobtypeUrl)\r\n");
      out.write("		        .then(response => response.json())\r\n");
      out.write("		        .then(data => {\r\n");
      out.write("		        	debugger;\r\n");
      out.write("		            const jobTypeSelect = document.getElementById('jobTypeSelect');\r\n");
      out.write("		            data.jobTypeList.forEach(jobType => { // Assuming \"jobTypeList\" is the key used in the attribute\r\n");
      out.write("		                const option = document.createElement('option');\r\n");
      out.write("		                option.value = jobType.id;\r\n");
      out.write("		                option.textContent = jobType.name;\r\n");
      out.write("		                jobTypeSelect.appendChild(option);\r\n");
      out.write("		            });\r\n");
      out.write("		        })\r\n");
      out.write("		        .catch(error => {\r\n");
      out.write("		        	debugger;\r\n");
      out.write("		            console.log('Error:', error);\r\n");
      out.write("		        });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
