/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-18 06:08:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	if(session.getAttribute("email")==null){
		response.sendRedirect("login.jsp");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Freelancer - Start Bootstrap Theme</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.15.4/js/all.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/index-styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\"\r\n");
      out.write("		id=\"mainNav\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#page-top\">Unique Developer</a>\r\n");
      out.write("			<button\r\n");
      out.write("				class=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\"\r\n");
      out.write("				type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("				data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				Menu <i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#portfolio\">Portfolio</a></li>\r\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#about\">About</a></li>\r\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"\">Logout</a></li>\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Masthead-->\r\n");
      out.write("	<header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("		<div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("			<!-- Masthead Avatar Image-->\r\n");
      out.write("			<img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\"\r\n");
      out.write("				alt=\"...\" />\r\n");
      out.write("			<!-- Masthead Heading-->\r\n");
      out.write("			<h1 class=\"masthead-heading text-uppercase mb-0\">Welcome To Unique Developer</h1>\r\n");
      out.write("			<!-- Icon Divider-->\r\n");
      out.write("			<div class=\"divider-custom divider-light\">\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("				<div class=\"divider-custom-icon\">\r\n");
      out.write("					<i class=\"fas fa-star\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Masthead Subheading-->\r\n");
      out.write("			<p class=\"masthead-subheading font-weight-light mb-0\">Java\r\n");
      out.write("				Development - Web Development - Python</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- Portfolio Section-->\r\n");
      out.write("	<section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Portfolio Section Heading-->\r\n");
      out.write("			<h2\r\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\r\n");
      out.write("			<!-- Icon Divider-->\r\n");
      out.write("			<div class=\"divider-custom\">\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("				<div class=\"divider-custom-icon\">\r\n");
      out.write("					<i class=\"fas fa-star\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Portfolio Grid Items-->\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<!-- Portfolio Item 1-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal1\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/cabin.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Portfolio Item 2-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal2\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/cake.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Portfolio Item 3-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal3\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/circus.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Portfolio Item 4-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal4\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/game.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Portfolio Item 5-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal5\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/safe.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Portfolio Item 6-->\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#portfolioModal6\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/submarine.png\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- About Section-->\r\n");
      out.write("	<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- About Section Heading-->\r\n");
      out.write("			<h2\r\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("			<!-- Icon Divider-->\r\n");
      out.write("			<div class=\"divider-custom divider-light\">\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("				<div class=\"divider-custom-icon\">\r\n");
      out.write("					<i class=\"fas fa-star\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- About Section Content-->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 ms-auto\">\r\n");
      out.write("					<p class=\"lead\">Freelancer is a free bootstrap theme created by\r\n");
      out.write("						Start Bootstrap. The download includes the complete source files\r\n");
      out.write("						including HTML, CSS, and JavaScript as well as optional SASS\r\n");
      out.write("						stylesheets for easy customization.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 me-auto\">\r\n");
      out.write("					<p class=\"lead\">You can create your own custom avatar for the\r\n");
      out.write("						masthead, change the icon in the dividers, and add your email\r\n");
      out.write("						address to the contact form to make it fully functional!</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- About Section Button-->\r\n");
      out.write("			<div class=\"text-center mt-4\">\r\n");
      out.write("				<a class=\"btn btn-xl btn-outline-light\"\r\n");
      out.write("					href=\"https://startbootstrap.com/theme/freelancer/\"> <i\r\n");
      out.write("					class=\"fas fa-download me-2\"></i> Free Download!\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Contact Section-->\r\n");
      out.write("	<section class=\"page-section\" id=\"contact\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Contact Section Heading-->\r\n");
      out.write("			<h2\r\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Contact\r\n");
      out.write("				Me</h2>\r\n");
      out.write("			<!-- Icon Divider-->\r\n");
      out.write("			<div class=\"divider-custom\">\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("				<div class=\"divider-custom-icon\">\r\n");
      out.write("					<i class=\"fas fa-star\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"divider-custom-line\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Contact Section Form-->\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("					<!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("					<!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("					<!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("					<!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("					<!-- To make this form functional, sign up at-->\r\n");
      out.write("					<!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("					<!-- to get an API token!-->\r\n");
      out.write("					<form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("						<!-- Name input-->\r\n");
      out.write("						<div class=\"form-floating mb-3\">\r\n");
      out.write("							<input class=\"form-control\" id=\"name\" type=\"text\"\r\n");
      out.write("								placeholder=\"Enter your name...\" data-sb-validations=\"required\" />\r\n");
      out.write("							<label for=\"name\">Full name</label>\r\n");
      out.write("							<div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A\r\n");
      out.write("								name is required.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Email address input-->\r\n");
      out.write("						<div class=\"form-floating mb-3\">\r\n");
      out.write("							<input class=\"form-control\" id=\"email\" type=\"email\"\r\n");
      out.write("								placeholder=\"name@example.com\"\r\n");
      out.write("								data-sb-validations=\"required,email\" /> <label for=\"email\">Email\r\n");
      out.write("								address</label>\r\n");
      out.write("							<div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An\r\n");
      out.write("								email is required.</div>\r\n");
      out.write("							<div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email\r\n");
      out.write("								is not valid.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Phone number input-->\r\n");
      out.write("						<div class=\"form-floating mb-3\">\r\n");
      out.write("							<input class=\"form-control\" id=\"phone\" type=\"tel\"\r\n");
      out.write("								placeholder=\"(123) 456-7890\" data-sb-validations=\"required\" />\r\n");
      out.write("							<label for=\"phone\">Phone number</label>\r\n");
      out.write("							<div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A\r\n");
      out.write("								phone number is required.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Message input-->\r\n");
      out.write("						<div class=\"form-floating mb-3\">\r\n");
      out.write("							<textarea class=\"form-control\" id=\"message\" type=\"text\"\r\n");
      out.write("								placeholder=\"Enter your message here...\" style=\"height: 10rem\"\r\n");
      out.write("								data-sb-validations=\"required\"></textarea>\r\n");
      out.write("							<label for=\"message\">Message</label>\r\n");
      out.write("							<div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A\r\n");
      out.write("								message is required.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Submit success message-->\r\n");
      out.write("						<!---->\r\n");
      out.write("						<!-- This is what your users will see when the form-->\r\n");
      out.write("						<!-- has successfully submitted-->\r\n");
      out.write("						<div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("							<div class=\"text-center mb-3\">\r\n");
      out.write("								<div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("								To activate this form, sign up at <br /> <a\r\n");
      out.write("									href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Submit error message-->\r\n");
      out.write("						<!---->\r\n");
      out.write("						<!-- This is what your users will see when there is-->\r\n");
      out.write("						<!-- an error submitting the form-->\r\n");
      out.write("						<div class=\"d-none\" id=\"submitErrorMessage\">\r\n");
      out.write("							<div class=\"text-center text-danger mb-3\">Error sending\r\n");
      out.write("								message!</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Submit Button-->\r\n");
      out.write("						<button class=\"btn btn-primary btn-xl disabled\" id=\"submitButton\"\r\n");
      out.write("							type=\"submit\">Send</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Footer-->\r\n");
      out.write("	<footer class=\"footer text-center\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- Footer Location-->\r\n");
      out.write("				<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("					<p class=\"lead mb-0\">\r\n");
      out.write("						2215 John Daniel Drive <br /> Clark, MO 65243\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Footer Social Icons-->\r\n");
      out.write("				<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("					<a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("						class=\"fab fa-fw fa-facebook-f\"></i></a> <a\r\n");
      out.write("						class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("						class=\"fab fa-fw fa-twitter\"></i></a> <a\r\n");
      out.write("						class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("						class=\"fab fa-fw fa-linkedin-in\"></i></a> <a\r\n");
      out.write("						class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("						class=\"fab fa-fw fa-dribbble\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Footer About Text-->\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\r\n");
      out.write("					<p class=\"lead mb-0\">\r\n");
      out.write("						Freelance is a free to use, MIT licensed Bootstrap theme created\r\n");
      out.write("						by <a href=\"http://startbootstrap.com\">Start Bootstrap</a> .\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Copyright Section-->\r\n");
      out.write("	<div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<small>Copyright &copy; Your Website 2021</small>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modals-->\r\n");
      out.write("	<!-- Portfolio Modal 1-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal1\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Log\r\n");
      out.write("									Cabin</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/cabin.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modal 2-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal2\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Tasty\r\n");
      out.write("									Cake</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/cake.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modal 3-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal3\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Circus\r\n");
      out.write("									Tent</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/circus.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modal 4-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal4\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Controller</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/game.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modal 5-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal5\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Locked\r\n");
      out.write("									Safe</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/safe.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Portfolio Modal 6-->\r\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\"\r\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal6\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row justify-content-center\">\r\n");
      out.write("							<div class=\"col-lg-8\">\r\n");
      out.write("								<!-- Portfolio Modal - Title-->\r\n");
      out.write("								<h2\r\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Submarine</h2>\r\n");
      out.write("								<!-- Icon Divider-->\r\n");
      out.write("								<div class=\"divider-custom\">\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("									<div class=\"divider-custom-icon\">\r\n");
      out.write("										<i class=\"fas fa-star\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"divider-custom-line\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- Portfolio Modal - Image-->\r\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("									src=\"assets/img/portfolio/submarine.png\" alt=\"...\" />\r\n");
      out.write("								<!-- Portfolio Modal - Text-->\r\n");
      out.write("								<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("									adipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("									molestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("									asperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("									itaque. Nam.</p>\r\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">\r\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Core theme JS-->\r\n");
      out.write("	<script src=\"js/scripts.js\"></script>\r\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("	<!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("	<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("	<script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
